name: Docker Build and Push Beta

on:
  push:
    branches:
      - main

jobs:
  call-workflow-dockerhub-build-push:
    if: github.repository == 'NelsonDane/BingRewardsBeta'
    uses: NelsonDane/DockerHub-Actions/.github/workflows/dockerhub_build_push.yml@main
    with:
      dockerhub_repo_name: bing-rewards
      image_tag: beta
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
